# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 504aa48946d32e527a9f29cf66c9820c41008f46c5cf5391c3bd7897ffa94c3589b00ac0fa8dfda8505cde32cbd64f14399fdf5f1b86d34e62722c7e4d79677f

test:
  secret_key_base: cf1251aa08ab6ab1ec7de6c7205e6b1d367bb4e173e5fd49a716dbec9a2d84a447d29f7fe6686f7fd3724192af2e0a0d151264ad5e00ea2605b76c05dc1d1240

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
